### ISSUE TITLE
 No such namespace: react-dom

### ISSUE THREAD

**Issue by benjamin-asdf** [ampersanda/krell-template-runner#8]
```[benj@benj-pc AwesomeProject]$ clj -m krell.main -co build.edn -c -r
WARNING: Implicit use of clojure.main with options is deprecated, use -M
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
clojure.lang.ExceptionInfo: failed compiling file:/home/benj/.cljs/.aot_cache/0.0.1212689677/5C26A0D/reagent/dom.cljs {:file #object[java.io.File 0x7ebe5795 "/home/benj/.cljs/.aot_cache/0.0.1212689677/5C26A0D/reagent/dom.cljs"], :clojure.error/phase :compilation}
        at cljs.compiler$compile_file$fn__5090.invoke(compiler.cljc:1720)
        at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1680)
        at cljs.compiler$compile_file.invoke(compiler.cljc:1656)
        at cljs.closure$compile_file.invokeStatic(closure.clj:663)
        at cljs.closure$compile_file.invoke(closure.clj:641)
        at cljs.closure$eval7485$fn__7486.invoke(closure.clj:737)
        at cljs.closure$eval7388$fn__7389$G__7377__7396.invoke(closure.clj:559)
        at cljs.closure$compile_from_jar.invokeStatic(closure.clj:713)
        at cljs.closure$compile_from_jar.invoke(closure.clj:700)
        at cljs.closure$eval7491$fn__7492.invoke(closure.clj:747)
        at cljs.closure$eval7388$fn__7389$G__7377__7396.invoke(closure.clj:559)
        at cljs.closure$compile_sources$iter__7625__7629$fn__7630.invoke(closure.clj:1107) 
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5403.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3130)
        at clojure.core$doall.invokeStatic(core.clj:3136)
        at clojure.core$doall.invoke(core.clj:3136)
        at cljs.closure$compile_sources.invokeStatic(closure.clj:1103)
        at cljs.closure$compile_sources.invoke(closure.clj:1092)
        at cljs.closure$build.invokeStatic(closure.clj:3115)
        at cljs.closure$build.invoke(closure.clj:3023)
        at cljs.build.api$build.invokeStatic(api.clj:227)
        at cljs.build.api$build.invoke(api.clj:210)
        at cljs.cli$default_compile.invokeStatic(cli.clj:530)
        at cljs.cli$default_compile.invoke(cli.clj:486)
        at krell.repl$krell_compile.invokeStatic(repl.clj:314)
        at krell.repl$krell_compile.invoke(repl.clj:305)
        at cljs.cli$compile_opt.invokeStatic(cli.clj:540)
        at cljs.cli$compile_opt.invoke(cli.clj:538)
        at cljs.cli$main.invokeStatic(cli.clj:701)
        at cljs.cli$main.doInvoke(cli.clj:690)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at cljs.main$_main.invokeStatic(main.clj:65)
        at cljs.main$_main.doInvoke(main.clj:56)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at krell.main$_main.invokeStatic(main.clj:9)
        at krell.main$_main.doInvoke(main.clj:7)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
Caused by: clojure.lang.ExceptionInfo: null #:clojure.error{:source nil, :line nil, :column nil, :phase :compilation}
        at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:4252)
        at cljs.analyzer$analyze.invoke(analyzer.cljc:4238)
        at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1538)
        at cljs.compiler$emit_source.invoke(compiler.cljc:1511)
        at cljs.compiler$compile_file_STAR_$fn__5059.invoke(compiler.cljc:1623)
        at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1431)
        at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1420)
        at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1607)
        at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1600)
        at cljs.compiler$compile_file$fn__5090.invoke(compiler.cljc:1705)
        ... 53 more
Caused by: clojure.lang.ExceptionInfo: No such namespace: react-dom, could not locate react_dom.cljs, react_dom.cljc, or JavaScript source providing "react-dom" (Please check that namespaces with dashes use underscores in the ClojureScript file name) in file /home/benj/.cljs/.aot_cache/0.0.1212689677/5C26A0D/reagent/dom.cljs {:tag :cljs/analysis-error}
        at cljs.analyzer$error.invokeStatic(analyzer.cljc:762)
        at cljs.analyzer$error.invoke(analyzer.cljc:758)
        at cljs.analyzer$error.invokeStatic(analyzer.cljc:760)
        at cljs.analyzer$error.invoke(analyzer.cljc:758)
        at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2636)
        at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2605)
        at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:4114)
        at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:4109)
        at cljs.analyzer$analyze_STAR_$fn__3719.invoke(analyzer.cljc:4236)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6829)
        at clojure.core$reduce.invoke(core.clj:6812)
        at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:4236)
        at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:4227)
        at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:4255)
        ... 62 more
```

I came from a complete bare setup. If there are dependencies it would be helpful if the readme says it or there is an error/warning.

**Comment by ampersanda** [comment]
Fixed in 8f2fa6a — thanks for the report!

**What was wrong:** the template was pinning an old version of Reagent (`0.10.0`). That version tries to load React's web renderer (`react-dom`), which doesn't exist in a React Native app. That's the `No such namespace: react-dom` error shown.

**What to do:**
- If you're starting fresh: just re-run the `curl … | bash -s YourProject` command. The scaffolder now generates a working `deps.edn`.
- If you want to fix an existing project, update its `deps.edn` to:
  ```edn
  {:deps {io.vouch/krell {:git/url "https://github.com/vouch-opensource/krell.git"
                          :sha "08f2bfea96aa48feb8511851e37f5948453986e5"}
          io.vouch/reagent-react-native {:git/url "https://github.com/vouch-opensource/reagent-react-native.git"
                                         :sha "dc4a6730e0da3f8b99243b1fd0912a5c802b43bc"}
          reagent/reagent {:mvn/version "1.2.0"
                           :exclusions [cljsjs/react cljsjs/react-dom]}}}
  ```

The `clojure.main is deprecated` warning is gone too and the README now uses `clj -M -m krell.main …` instead of `clj -m krell.main …`.
